name: bloc_architecture
description: Bloc Pattern with Clean Code architecture and flutter gen
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  #network
  http:
  dio:
  dartz:

  #state_managment
  flutter_bloc:
  equatable:
  get_it:

  #UI
  flutter_svg:
  lottie:
  modal_bottom_sheet:
  dropdown_button2:
  cupertino_icons:

  #storage
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  flutter_gen:
  flutter_gen_runner:
  flutter_launcher_icons:
  shared_preferences_platform_interface:
  flutter_lints: ^2.0.0

flutter_gen:
  integration:
    flutter_svg:

  colors:
    inputs:
      - assets/colors/colors.xml
flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
